name: Build Project

on:
  workflow_call:
    inputs:
      preset:
        description: >
          CMake preset to build the project, run
          `cmake --list-presets` to see options
        required: false
        type: string
        default: 'nucleo-debug'
    outputs:
      build-artifact:
        description: 'Build result artifact id for later use'
        value: ${{ jobs.build.outputs.build-artifact }}

  workflow_dispatch:
    inputs:
      preset:
        description: >
          CMake preset to build the project, run
          `cmake --list-presets` to see options
        required: false
        type: string
        default: 'nucleo-debug'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/hyperloop-upv/hyperloop-firmware-toolchain:latest

    outputs:
      build-artifact: ${{ steps.upload-build-artifact.outputs.artifact-id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Init submodules
        run: |
          git config --global --add safe.directory '*'
          ./tools/init-submodules.sh 
        shell: bash

      - name: Build
        run: |
          cmake --preset ${{ inputs.preset }}
          cmake --build --preset ${{ inputs.preset }}
        shell: bash
