name: Build and Tests  CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    name: Build ST-LIB
    strategy:
      matrix:
        build_type: [hardware,simulator]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - run: arm-none-eabi-gcc --version
      - name: Build 
        run: ./build ${{matrix.build_type}}
  Run Tests:
    name: Run Simulator tests
    needs: build