name: Build and Tests  CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    name: Build ST-LIB
    strategy:
      matrix:
        build_type: [hardware,simulator]
    runs-on: ubuntu-24.04
    container:
      image: jmaralo/hyperloop-upv-firmware:0.2.0
    steps:
      - name: Clone ST-LIB
        uses: actions/checkout@v3
      - name: Build 
        run: ./tools/build.sh ${{matrix.build_type}}
        ## the following is because of this known limitation
        ## https://github.com/actions/download-artifact?tab=readme-ov-file#limitations
      - name: 'Tar files'
        run:  ./tools/tar_tests.sh ${{matrix.build_type}}
        continue-on-error: true
      - name: Upload test-binary
        uses: actions/upload-artifact@v4
        with:
          name: stlib_test
          path: test_files.tar
          retention-days: 1
        #this is because hardware build doesnot create the 
        # test executable
        continue-on-error: true