name: Build and Tests  CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    name: Build ST-LIB
    strategy:
      matrix:
        build_type: [hardware,simulator]
    runs-on: ubuntu-22.04
    steps:
      - name: Clone ST-LIB
        uses: actions/checkout@v3
      - name: Clone cubeclt
        uses: actions/checkout@v3
        with:
          repository: HyperloopUPV-H8/cubeclt
      - name: Install cubeclt
        run: |
          cd cubeclt
          git lfs pull
          chmod +x cubeclt_1.16.0_installer.sh
          echo | LICENSE_ALREADY_ACCEPTED=1 sudo ./cubeclt_1.16.0_installer.sh
      - name: Build 
        run: ./tools/build.sh ${{matrix.build_type}}
        ## the following is because of this known limitation
        ## https://github.com/actions/download-artifact?tab=readme-ov-file#limitations
      - name: 'Tar files'
        run:  ./tools/tar_tests.sh ${{matrix.build_type}}
        continue-on-error: true
      - name: Upload test-binary
        uses: actions/upload-artifact@v4
        with:
          name: stlib_test
          path: test_files.tar
          retention-days: 1
        #this is because hardware build doesnot create the 
        # test executable
        continue-on-error: true
  Run-Tests:
    name: Run Simulator tests
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Download test binary compressed
        uses: actions/download-artifact@v4
        with:
          name: stlib_test
      - run: tar -xvf test_files.tar
      - name: Run test
        run: ./tools/run_sim_tests.sh
